name: 'Setup Kirby environment'
description: 'Will checkout the repository, install node, install npm dependencies either from a cache or as a clean install'
inputs: 
  node-version: # Composite steps does not support env - added node version as input instead for DRYness
      description: 'Node version to be used for setup'
      required: false 
      default: '14.16'
runs: 
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{secrets.VERSION_BUMP_GITHUB_TOKEN}}
    - name: Get Node.JS version from package.json
      run: echo "NODE_VERSION=$(jq -r .engines.node ./package.json)" >> $GITHUB_ENV
      shell: bash
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: Fetch Node Modules Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: | 
          **/node_modules
        key: node-modules-${{ runner.os }}-${{ inputs.node-version }}-${{hashFiles('**/package.json')}}-${{hashFiles('**/package-lock.json')}}
    - name: Last steps
      run: echo ------------- POST -----------------
      shell: bash
    - name: Clean Install NPM Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
    - name: Run Postinstall Script
      if: steps.cache.outputs.cache-hit == 'true'
      run: npm run postinstall
      shell: bash
