name: 'Setup Kirby environment'
description: 'Will checkout the repository, install node, install npm dependencies either from a cache or as a clean install'
runs:
  using: 'composite'
  steps:
      - name: Get Node.JS version from package.json
        run: echo "NODE_VERSION=$(jq -r .engines.node ./package.json)" >> $GITHUB_ENV
        shell: bash
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Echo Node.JS version from package.json
        run: echo ${{env.NODE_VERSION}}
        shell: bash
      - name: LS
        run: ls
        shell: bash     
      - name: Fetch Node Modules Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
          key: node-modules-${{ runner.os }}-${{ inputs.node-version }}-${{hashFiles('**/package.json')}}-${{hashFiles('**/package-lock.json')}}
      - name: Clean Install NPM Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Postinstall Script
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run postinstall
