#env:
#  global:
#  - NODE_VERSION=10
#  - EMULATOR_API_LEVEL=25
#  - ANDROID_VERSION=25
#  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
#  - ANDROID_ABI=armeabi-v7a
#  - APPIUM_VERSION=1.7.0
#  - EMULATOR_NAME=test
#  - ANDROID_TAG=google_apis

matrix:
  include:
  - stage: "Build"
    os: osx
    env:
    - Build="iOS"
    osx_image: xcode9.3
    language: node_js
    node_js: "10"
    jdk: oraclejdk8
    before_install:
    - npm install
    before_script:
    - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision
    - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer
    - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12
    # Create a custom keychain
    - security create-keychain -p travis ios-build.keychain
    # Make the custom keychain default, so xcodebuild will use it for signing
    - security default-keychain -s ios-build.keychain
    # Unlock the keychain
    - security unlock-keychain -p travis ios-build.keychain
    # Set keychain timeout to 1 hour for long builds
    # see http://www.egeek.me/2013/02/23/jenkins-and-xcode-user-interaction-is-not-allowed/
    - security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
    # Add certificates to keychain and allow codesign to access them
    - security import $TRAVIS_BUILD_DIR/scripts/certs/AppleWWDRCA.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
    - security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
    - security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
    # Put the provisioning profile in place
    - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
    - cp "$TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/
    script:
    - echo n | tns build ios --provision 'dkkirbydesignsystem.mobileprovision' --for-device --bundle

android:
  licenses:
  - ".+"

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable

deploy:
  provider: releases
  file: $TRAVIS_BUILD_DIR/platforms/ios/build/device/designsystem.ipa
  file_glob: "true"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    repo: kirbydesign/designsystem
    tags: true

#install:
#- nvm install $NODE_VERSION
#- npm install -g typings
#- wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
#- npm install -g nativescript.tgz --ignore-scripts
#- tns usage-reporting disable
#- tns error-reporting disable