os: osx
sudo: required
osx_image: xcode9.4
language: node_js
node_js: "10.5"

jdk: oraclejdk8

install:
  - sudo gem install xcodeproj
  - sudo gem install cocoapods
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew cask install android-sdk
  - export ANDROID_SDK_ROOT=/usr/local/share/android-sdk
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
  - yes | sdkmanager "build-tools;26.0.2"
  - yes | sdkmanager "platform-tools"
  - yes | sdkmanager "tools"
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "extras;android;m2repository"
  - sudo pod setup
  - pip install six
  - npm install
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
  #- sudo tns setup
  - sudo tns cloud setup
  - tns doctor

before_script:
  - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision
  - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer
  - openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12
  # Create a custom keychain
  - security create-keychain -p travis ios-build.keychain
  # Make the custom keychain default, so xcodebuild will use it for signing
  - security default-keychain -s ios-build.keychain
  # Unlock the keychain
  - security unlock-keychain -p travis ios-build.keychain
  # Set keychain timeout to 1 hour for long builds
  # see http://www.egeek.me/2013/02/23/jenkins-and-xcode-user-interaction-is-not-allowed/
  - security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
  # Add certificates to keychain and allow codesign to access them
  - security import $TRAVIS_BUILD_DIR/scripts/certs/AppleWWDRCA.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
  # Put the provisioning profile in place
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp "$TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/

script:
  - sudo tns build ios --bundle --for-device --provision dk.kirby.design.system --release