env:
  global:
  - ANDROID_PACKAGE='designsystem.apk'
  - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/platforms/android/app/build/outputs/apk/debug/
  #- ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$ANDROID_PACKAGE?overwrite=true"
  - IOS_PACKAGE='designsystem.zip'
  - IOS_APP_NAME='designsystem.app'
  - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/platforms/ios/build/emulator
  #- IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$IOS_PACKAGE?overwrite=true"
branches:
  only:
  - master

matrix:
  include:
  - stage: "Build"
    os: osx
    env:
    - BuildiOS="11"
    - Xcode="9.4"
    osx_image: xcode9.4
    language: node_js
    node_js: "10.5"
    jdk: oraclejdk8
    script:
    - tns build ios --env.aot --env.uglify
    #- cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE $IOS_APP_NAME
    #- "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE --data-binary @$IOS_PACKAGE_FOLDER/$IOS_PACKAGE"
  - language: android
    env:
    - BuildAndroid="26"
    os: linux
    jdk: oraclejdk8
    before_install: nvm install 8.9.1
    script:
    - tns build android --env.aot --env.uglify --env.snapshot
    #- "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $ANDROID_SAUCE_STORAGE --data-binary @$ANDROID_PACKAGE_FOLDER/app-debug.apk"

  #matrix:
  #  include:
    #  - stage: "Build"
    #os: osx
    #env:
    #- Build="iOS"
    #osx_image: xcode9.4
    #language: node_js
    #node_js: "10.5"
    #jdk: oraclejdk8
    #before_install:
    #- npm install
    #before_script:
    #- openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision
    #- openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer
    #- openssl aes-256-cbc -k "$SECURITY_PASSWORD" -in $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12.enc -d -a -out $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12
    # Create a custom keychain
    #- security create-keychain -p travis ios-build.keychain
    # Make the custom keychain default, so xcodebuild will use it for signing
    #- security default-keychain -s ios-build.keychain
    # Unlock the keychain
    #- security unlock-keychain -p travis ios-build.keychain
    # Set keychain timeout to 1 hour for long builds
    # see http://www.egeek.me/2013/02/23/jenkins-and-xcode-user-interaction-is-not-allowed/
    #- security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
    # Add certificates to keychain and allow codesign to access them
    #- security import $TRAVIS_BUILD_DIR/scripts/certs/AppleWWDRCA.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
    #- security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
    #- security import $TRAVIS_BUILD_DIR/scripts/certs/dkkirbydesignsystem-key.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
    # Put the provisioning profile in place
    #- mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
    #- cp "$TRAVIS_BUILD_DIR/scripts/profile/dkkirbydesignsystem.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/
    #- sudo gem install xcodeproj
    #- sudo gem install cocoapods
    #- pod setup
    #- pip install six
#    - tns cloud setup
#    - tns doctor
#    script:
#    - echo n | tns build ios --bundle --for-device --provision dk.kirby.design.system --release

#android:
#  licenses:
#  - ".+"

install:
  - brew cask install android-sdk
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - $ANDROID_HOME/tools/bin/sdkmanager "tools" "emulator" "platform-tools" "platforms;android-25" "build-tools;27.0.3" "extras;android;m2repository" "extras;google;m2repository"
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable

deploy:
  provider: releases
  file: $TRAVIS_BUILD_DIR/platforms/ios/build/device/designsystem.ipa
  file_glob: "true"
  skip_cleanup: false
  overwrite: true
  on:
    branch: master
    repo: kirbydesign/designsystem
    tags: true

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-26
  - android-23
  - extra-android-m2repository

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - .nvm
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/