#env:
#  global:
#  - NODE_VERSION=10
#  - EMULATOR_API_LEVEL=25
#  - ANDROID_VERSION=25
#  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
#  - ANDROID_ABI=armeabi-v7a
#  - APPIUM_VERSION=1.7.0
#  - EMULATOR_NAME=test
#  - ANDROID_TAG=google_apis

matrix:
  include:
  - stage: "Build"
    os: osx
    env:
    - Build="iOS"
    osx_image: xcode9.3
    language: node_js
    node_js: "10"
    jdk: oraclejdk8
    before_install:
    - npm install
    script:
    - echo n | tns build ios --for-device --bundle

android:
  licenses:
  - ".+"

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable

deploy:
  provider: releases
  file: "designsystem/platforms/ios/build/device/designsystem.ipa"
  file_glob: "true"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    repo: kirbydesign/designsystem
    tags: true

#install:
#- nvm install $NODE_VERSION
#- npm install -g typings
#- wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
#- npm install -g nativescript.tgz --ignore-scripts
#- tns usage-reporting disable
#- tns error-reporting disable