{{- if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1" }}
{{- if .Values.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "spa.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spa.name" . }}
spec:
  secretName: {{ template "spa.fullname" . }}-secret
  dnsNames:
{{- range .Values.ingress }}
  - {{ .domain }}
{{- end }}
  acme:
    config:
    - http01:
        ingressClass: 'addon-http-application-routing'
      domains:
{{- range .Values.ingress }}
      - {{ .domain }}
{{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
{{- end }}
