apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spa.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spa.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ template "spa.name" . }}
    spec:
      containers:
      - name: {{ template "spa.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: "{{ .Values.configPath }}"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 20Mi
        livenessProbe:
          httpGet:
            path: /index.html
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /index.html
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 5
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "spa.fullname" . }}
