name: GitHub Actions Demo
on:
  push:
    tags:
      - 'vtest[0-9]+'
defaults:
  run:
    shell: bash
jobs:
  say-hello-test:
    name: Say hello test
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo Hello World.
          branchname="${{ github.head_ref || github.ref }}"
          echo "Github branchname: ${branchname}"