name: GitHub Actions Demo
on:
  push:
    tags:
      - 'vtest[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  say-hello-test:
    name: Say hello test
    runs-on: ubuntu-latest
    env:
      DOMAIN: 'kirby.design'
    steps:
      - name: Pre
        run: echo Running...
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get deployment name for develop or feature branch
        if: "github.event_name == 'pull_request' || github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo Hello feature Branch.
          branchname="${{ github.head_ref || github.ref }}"
          echo "Github feature branchname: ${branchname}"
      - name: Get hostname for release branch
        if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')"
        shell: bash
        run: |
          set -e
          echo Hello Release Branch.
          tagname="${{ github.ref }}"
          echo "Github tag: ${tagname}"
          echo 3333
          branchname=$(git branch -r --contains ${{ github.ref }})
          echo "Github release branchname: ${branchname}"
          branchname="${branchname##*/}"
          echo "Removed leading paths - branchname: ${branchname}"
          echo 33333
          git branch
          test="XX"
          echo "Github test: ${test}"
          which git
      - name: Post
        run: echo End!

